# Generated by Django 6.0.1 on 2026-02-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_text_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_types',
            new_name='type',
        ),
    ]
